### ISSUE TITLE
examples.py doesn't run

### ISSUE THREAD

**Issue by r-williams-2** [ankushaggarwal/pymecht#3]
I was intending to base some tests/examples on the examples.py script. Most work. However, `femex()` fails in the `consistency_check_compute()` function of the `LinearFEM1D` class.

It appears that `self._compute()` is overridden by the definition of `self.compute = uniax`, where `uniax(dy, **kwargs)`. However, no positional arguments (`dy`) are passed to the `self._compute(dof=y+eps,deriv=dy,location=X,eid=0)` function in the class definition.

I'm not entirely sure what the functionality should be to debug myself. Is it intended that the value of `dy` calculated in the `LinearFEM1D` class be used in `uniax(dy, **kwargs)`?

**Comment by ankushaggarwal** [comment]
LinearFEM1D is now removed. The examples.py runs now.

**Comment by ankushaggarwal** [comment]
LinearFEM1D is now removed. The examples.py runs now.
